# Generated by Django 3.1.3 on 2020-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abschluss',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auslandserfahrung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='empfehlungsschreiben',
            field=models.FileField(blank=True, default=None, null=True, upload_to='recommendationletters'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.FloatField(default=4.0),
        ),
    ]
